config/routes.rb
Rails.application.routes.draw do

  resources :loanapps

  root 'welcomepage#index'

end

app/models/loanapp.rb
class Loanapp < ActiveRecord::Base
	attr_accessible :jméno, :příjmení, :telefon, :email, :zdroj_příjmu, :průměrná_výše_měsíčního_příjmu, :povinné_měsíční_výdaje, :výše_půjčky, :doba_splácení, :císlo_účtu
	attr_writer :current_step

validates_presence_of :jméno, :if => lambda { |o| o.current_step == "details" }
validates_presence_of :zdroj_příjmu, :if => lambda { |o| o.current_step == "income" }
validates_presence_of :výše_půjčky, :if => lambda { |o| o.current_step == "product" }


	def current_step
		@current_step || steps.first
	end

	def steps
		%w[details income product confirm]
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/loanapps_controller.rb
class LoanappsController < ApplicationController
	def new
		@loanapp = Loanapp.new
	end

	def create
		@loanapp = Loanapp.new(params[:loanapp])

		@loanapp.save
		redirect_to @loanapp
	end
end

app/controllers/welcomepage_controller.rb
class WelcomepageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loanapps_helper.rb
module LoanappsHelper
end

app/helpers/welcomepage_helper.rb
module WelcomepageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsobRailsDemo</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="css/main40ab.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/ideas">Ideas</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Etnetera Demo 2014
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/loanapps/confirm_step.html.erb
     <h2>Potvrďte Informace</h2>

  <p>
    <strong></strong>
    <%=h @loanapp.jméno %>
  </p>

  <p>
    <strong></strong>
    <%=h @loanapp.příjmení %>
  </p>

   <p>
    <strong></strong>
    <%=h @loanapp.telefon %>
  </p>

    <p>
    <strong></strong>
    <%=h @loanapp.email %>
  </p>

   <p>
    <strong></strong>
    <%=h @loanapp.adresa %>
  </p>

  <p>
    <strong></strong>
    <%=h @loanapp.psč %>
  </p>

  <p>
    <strong></strong>
    <%=h @loanapp.zdroj_příjmu %>
  </p>

  <p>
    <strong></strong>
    <%=h @loanapp.průměrná_výše_měsíčního_příjmu %>
  </p>

  <p>
    <strong></strong>
    <%=h @loanapp.povinné_měsíční_výdaje %>
  </p>

  <p>
    <strong></strong>
    <%=h @loanapp.výše_půjčky %>
  </p>

  <p>
    <strong></strong>
    <%=h @loanapp.doba_splácení %>
  </p>

  <p>
    <strong></strong>
    <%=h @loanapp.císlo_účtu %>
  </p>  

app/views/loanapps/details_step.html.erb
<h2>Osobní údaje</h2>

  <p>
    <%= f.label :jméno %><br>
    <%= f.text_field :jméno %>
  </p>

    <p>
    <%= f.label :příjmení %><br>
    <%= f.text_field :příjmení %>
  </p>

    <p>
    <%= f.label :telefon %><br>
    <%= f.text_field :telefon %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :adresa %><br>
    <%= f.text_field :adresa %>
  </p>

  <p>
    <%= f.label :psč %><br>
    <%= f.text_field :psč %>
  </p>

app/views/loanapps/income_step.html.erb
 <h2>Příjmy a výdaje</h2>

  <p>
    <%= f.label :zdroj_příjmu %><br>
    <%= f.text_field :zdroj_příjmu %>
  </p>

    <p>
    <%= f.label :průměrná_výše_měsíčního_příjmu %><br>
    <%= f.text_field :průměrná_výše_měsíčního_příjmu %>
  </p>

    <p>
    <%= f.label :povinné_měsíční_výdaje %><br>
    <%= f.text_field :povinné_měsíční_výdaje %>
  </p>

app/views/loanapps/new.html.erb
<h1>New Loan Application</h1>

<%= form_for @loanapp do |f| %>

<%= render "#{@loanapp.current_step}_step", :f => f %>
 
  <p>
    <%= f.submit "Odeslat žádost" %>
  </p>
<% end %>

<p><%= link_to "Back to List", loanapps_path %></p>

app/views/loanapps/product_step.html.erb
    <h2>Parametry produktu</h2>

  <p>
    <%= f.label :výše_půjčky %><br>
    <%= f.text_field :výše_půjčky %>
  </p>

    <p>
    <%= f.label :doba_splácení %><br>
    <%= f.text_field :doba_splácení %>
  </p>

    <p>
    <%= f.label :císlo_účtu %><br>
    <%= f.text_field :císlo_účtu %>
  </p>

app/views/welcomepage/index.html.erb
<h1>Hello, visitor!</h1>
<p>Find me in app/views/welcomepage/index.html.erb</p>